# Generated by Django 2.1.5 on 2020-01-09 06:30

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('image', models.ImageField(upload_to='banner/%Y/%m/%d', verbose_name='图片')),
                ('url', models.URLField(verbose_name='跳转链接')),
                ('name', models.CharField(max_length=50, verbose_name='图片描述')),
            ],
            options={
                'verbose_name': '轮廓图',
                'verbose_name_plural': '轮廓图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('name', models.CharField(max_length=10, verbose_name='类名')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('name', models.CharField(max_length=10, verbose_name='公司名称')),
                ('conpany_info', models.CharField(max_length=255, verbose_name='公司介绍')),
                ('video', models.FileField(upload_to='video/%Y/%m/%d', verbose_name='视屏')),
            ],
            options={
                'verbose_name': '公司简介',
                'verbose_name_plural': '公司简介',
            },
        ),
        migrations.CreateModel(
            name='Dbz_nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('name', models.CharField(max_length=8, verbose_name='导航名字')),
            ],
            options={
                'verbose_name': '导航',
                'verbose_name_plural': '导航',
            },
        ),
        migrations.CreateModel(
            name='Join_hands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('company_info', models.CharField(max_length=255, verbose_name='公司简介')),
                ('company_logo', models.ImageField(upload_to='logo/%Y/%m/%d', verbose_name='公司图片')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('cover', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='封面')),
                ('news_info', models.CharField(max_length=50, verbose_name='文章简介')),
                ('content', DjangoUeditor.models.UEditorField()),
                ('name', models.CharField(max_length=25, verbose_name='文章名字')),
                ('browse', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('cover', models.ImageField(upload_to='product/%Y/%m/%d', verbose_name='产品样式')),
                ('name', models.CharField(max_length=20, verbose_name='产品名字')),
                ('sub_title', models.CharField(max_length=30, verbose_name='副标题')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('phont', models.ImageField(upload_to='phont/%Y/%m/%d', verbose_name='员工头像')),
                ('job', models.CharField(max_length=10, verbose_name='职位')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
            ],
            options={
                'verbose_name': '客户表',
                'verbose_name_plural': '客户表',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbz_new.Product'),
        ),
    ]
