# Generated by Django 2.1.5 on 2020-01-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='跟新时间')),
                ('name', models.CharField(max_length=10, verbose_name='二级菜单名字')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单',
            },
        ),
    ]
